image: node:15.6

stages:
  - build

Build Nitro:
  stage: build
  script:
    - npm i
    - cp src/index.html.example src/index.html
    - npm run build-prod
  cache:
    key: ${CI_COMMIT_BRANCH}
    paths:
      - node_modules
